#ifndef EVENT_HANDLING_ENUM_H
#define EVENT_HANDLING_ENUM_H
#include "gui_enums.h"


#define SCKOL_PART 35
#define W_MIN_SCKROL_AREA WIDTH_MAIN_WINDOW / SCKOL_PART
#define W_MAX_SCKROL_AREA WIDTH_MAIN_WINDOW - (WIDTH_MAIN_WINDOW / SCKOL_PART)

#define H_MIN_SCKROL_AREA HEIGHT_MAIN_WINDOW / SCKOL_PART
#define H_MAX_SCKROL_AREA HEIGHT_MAIN_WINDOW - (HEIGHT_MAIN_WINDOW / SCKOL_PART)


#endif // EVENT_HANDLING_ENUM_H
