#ifndef HUMANUNITS_H
#define HUMANUNITS_H

#define ACCURACY_SPEED_FACTOR 100

//Colony center
#define HUM_COLONY_CENTER_PRODUCTION 50
#define HUM_COLONY_CENTER_TRANSPORT_HANGAR 3

//Transport
#define HUM_SHUTL_TRANSPORT_COST 300
#define HUM_SHUTL_TRANSPORT_SPEED 1
#define HUM_SHUTL_TRANSPORT_ACTIVITY_RANGE 5
#define HUM_SHITL_COLONISTS_CAPACITY 500
#define HUM_SHUTL_COLONISTS_ADMISSION 100


#endif // HUMANUNITS_H
