#ifndef HUMANUNITS_H
#define HUMANUNITS_H

//Colony center
#define HUM_COLONY_CENTER_PRODUCTION 50
#define HUM_COLONY_CENTER_TRANSPORT_HANGAR 2

//Transport
#define HUM_SHUTL_TRANSPORT_COST 300
#define HUM_SHUTL_TRANSPORT_SPEED 1
#define HUM_SHUTL_TRANSPORT_ACTIVITY_RANGE 5


#endif // HUMANUNITS_H
