#ifndef MODULEGENERATORSATTINGS_H
#define MODULEGENERATORSATTINGS_H

#define GENERATED_MAP_WIDTH 100
#define GENERATED_MAP_HEIGHT 100

enum Direction
{
    NODIR,
    UP,
    DOWN,
    LEFT,
    RIGHT
};

#endif // MODULEGENERATORSATTINGS_H
